repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      # - id: end-of-file-fixer
      # - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      # Python-specific
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements

  - repo: https://github.com/crate-ci/typos
    rev: v1.19.0
    hooks:
      - id: typos

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        pass_filenames: false
        args: [--package=guppylang]
        additional_dependencies: [
          graphviz,
          networkx,
          ormsgpack,
          pydantic,
          pytket,
          ]

  - repo: local
    hooks:
      - id: cargo-check
        name: Cargo check
        entry: bash -c 'cd validator && exec cargo check'
        pass_filenames: false
        types: [file, rust]
        language: system
      - id: rust-linting
        name: Rust linting
        entry: bash -c 'cd validator && exec cargo fmt --all --'
        pass_filenames: true
        types: [file, rust]
        language: system
      - id: rust-clippy
        name: Rust clippy
        entry: bash -c 'cd validator && exec cargo clippy --all-targets --all-features -- -Dclippy::all'
        pass_filenames: false
        types: [file, rust]
        language: system
