repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    # -   id: trailing-whitespace
    # Python-specific
    - id: check-ast
    - id: check-docstring-first
    - id: debug-statements

-   repo: https://github.com/crate-ci/typos
    rev: v1.16.23
    hooks:
    -   id: typos
        args: []

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.7
    hooks:
      - id: ruff
        # args: [--fix, --exit-non-zero-on-fix]
    #   - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.3.0'
    hooks:
    - id: mypy
      pass_filenames: false
      args: [--package=guppy]
      additional_dependencies: [
        ormsgpack,
        pydantic,
      ]

-   repo: local
    hooks:
    -   id: cargo-check
        name: Cargo check
        entry: bash -c 'cd validator && exec cargo check'
        pass_filenames: false
        types: [file, rust]
        language: system
    -   id: rust-linting
        name: Rust linting
        entry: bash -c 'cd validator && exec cargo fmt --all --'
        pass_filenames: true
        types: [file, rust]
        language: system
    -   id: rust-clippy
        name: Rust clippy
        entry: bash -c 'cd validator && exec cargo clippy --all-targets --all-features -- -Dclippy::all'
        pass_filenames: false
        types: [file, rust]
        language: system
