[tool.poetry]
name = "guppylang"
version = "0.1.0"
description = ""
authors = ["Mark Koch <mark.koch@quantinuum.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/CQCL/guppy"

[tool.poetry.dependencies]
python = "^3.10"
graphviz = "^0.20.1"
networkx = "^3.2.1"
ormsgpack = "^1.4.1"
pydantic = "^2.5.3"
typing-extensions = "^4.9.0"
pytket = { version = "^1.24.0", optional = true }
tket2-py = { git = "https://github.com/CQCL/tket2.git", optional = true, rev = "9e941f3" }

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
mypy = "^1.8.0"
pre-commit = "^3.6.0"
ruff = "^0.1.11"
maturin = "^1.4.0"
pytket = "*"

[tool.poetry.extras]
pytket = ["pytket", "tket2-py"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = ["pydantic.mypy"]
strict = true
allow_redefinition = true
# mypy doesn't support TypeAliasType fully yet
# https://github.com/python/mypy/issues/16614
disable_error_code = "valid-type"
