[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "guppy"
authors = [{name = "Mark Koch", email = "mark.koch@quantinuum.com"}]
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "graphviz",
    "networkx",
    "ormsgpack",
    "pydantic==1.10",
]

[project.optional-dependencies]
dev = [
    "pip-tools", # provides pip-compile
    "build",
    "pytest",
    "mypy",
    "black",
    "maturin>=1.1,<2.0",
]

[tool.setuptools]
py-modules = ["guppy"]

[tool.mypy]
plugins = [
    "pydantic.mypy"
]
strict = true
allow_redefinition = true
