[package]
name = "guppyval"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "guppyval"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
hugr = { git = "https://github.com/CQCL/hugr.git", rev = "1d09946deaa96dfa0304590508849091d3eede37" }
lazy_static = "1.4.0"
serde_json = "1.0.111"
