[package]
name = "validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quantinuum-hugr = { git = "https://github.com/CQCL-DEV/hugr.git" }
rmp-serde = "1.1.1"
