name: Pull Request

on: pull_request

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  check:
    name: Check Python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Guppy
        run: poetry install

      - name: Type check with mypy
        run: poetry run mypy guppylang

      - name: Check formatting with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./guppylang"
          args: format --check

      - name: Lint with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./guppylang"
          args: check

      - name: Install Guppy with validation
        run: poetry install --with validation

      - name: Run tests
        run: poetry run pytest

      - name: Install tket2 dependencies
        run: poetry install --with pytket

      - name: Rerun `py(...)` expression tests with tket2 installed
        run: poetry run pytest tests/integration/test_py.py tests/error/test_py_errors.py
