name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  merge_group:
    types: [checks_requested]
  workflow_dispatch: {}

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  check:
    name: Check Python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: install-llvm
        run: "sudo apt-get update && sudo apt-get install -y llvm-14"
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Guppy
        run: poetry install

      - name: Type check with mypy
        run: poetry run mypy guppylang

      - name: Check formatting with ruff
        run: poetry run ruff format --check guppylang

      - name: Lint with ruff
        run: poetry run ruff check guppylang

      - name: Install Guppy with validation and llvm-based execution
        run: poetry install --with execution,validation

      - name: Run tests
        run: poetry run pytest

      - name: Install tket2 dependencies
        run: poetry install --with pytket

      - name: Rerun `py(...)` expression tests and pytket lowering with tket2 installed
        run: poetry run pytest tests/integration/test_py.py tests/error/test_py_errors.py tests/integration/test_tket.py

  coverage:
    if: github.event_name != 'merge_group'
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: "poetry"

      - name: Install Guppy with validation, execution and pytket
        run: poetry install --with execution,pytket,validation

      - name: Run python tests with coverage instrumentation
        run: poetry run pytest --cov=./ --cov-report=xml

      - name: Upload python coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          name: python
          token: ${{ secrets.CODECOV_TOKEN }}
